export interface Person {
  givenName: string;
  surName: string;
  age: number;
  email: string;
  address: string;
}

export interface EPerson {
  givenName: string;
  surName: string;
  age: string;
  email: string;
  education: string;
}

export const ManyPerson: EPerson[] = [
  {
    givenName: 'Owen',
    surName: 'Jenkins',
    age: '45',
    email: 'o_jenkins@rocketmail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Michelle',
    surName: 'Murphy',
    age: '19',
    email: 'michellemurphy57@outlook.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Kevin',
    surName: 'Wright',
    age: '35',
    email: 'kevin.wright@yahoo.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Christopher',
    surName: 'Brown',
    age: '49',
    email: 'christopher_joseph_brown@live.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Michael',
    surName: 'Rogers',
    age: '69',
    email: 'michael_robert_rogers@gmail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Timothy',
    surName: 'Alexander',
    age: '66',
    email: 'timothy_george_alexander@hotmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Steven',
    surName: 'Lopez',
    age: '23',
    email: 'steven_richard_lopez@gmail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Stephen',
    surName: 'Walker',
    age: '49',
    email: 'srwalker@hotmail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Dylan',
    surName: 'Peterson',
    age: '56',
    email: 'dylanjohnpeterson@live.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Brandon',
    surName: 'Johnson',
    age: '26',
    email: 'b_j_johnson63@outlook.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Owen',
    surName: 'Butler',
    age: '32',
    email: 'o.butler@ymail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Thomas',
    surName: 'Morgan',
    age: '62',
    email: 't.r@live.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Owen',
    surName: 'Adams',
    age: '55',
    email: 'owen.r.adams@rocketmail.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Erin',
    surName: 'Perez',
    age: '59',
    email: 'e.f.perez@aol.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Evelyn',
    surName: 'Watson',
    age: '53',
    email: 'evelynwatson@hotmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Mateo',
    surName: 'Edwards',
    age: '74',
    email: 'mateo@aol.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Anna',
    surName: 'Gonzales',
    age: '20',
    email: 'a_n_gonzales@live.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'John',
    surName: 'Russell',
    age: '67',
    email: 'j_russell@rocketmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Justin',
    surName: 'Gray',
    age: '64',
    email: 'justin@ymail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Nathan',
    surName: 'White',
    age: '56',
    email: 'n_a_white76@yahoo.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Jasmine',
    surName: 'Jenkins',
    age: '57',
    email: 'jasmine_r_jenkins@outlook.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Brianna',
    surName: 'Carter',
    age: '54',
    email: 'b.g.carter@aol.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Sean',
    surName: 'Bennett',
    age: '21',
    email: 'sean_bennett@yahoo.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Isaac',
    surName: 'Rogers',
    age: '19',
    email: 'irrogers@ymail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Hannah',
    surName: 'Evans',
    age: '28',
    email: 'h.n.evans@hotmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Michelle',
    surName: 'James',
    age: '61',
    email: 'm_james@outlook.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Charlotte',
    surName: 'Stewart',
    age: '63',
    email: 'c.r.stewart@rocketmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Jeremy',
    surName: 'Foster',
    age: '29',
    email: 'jjfoster13@ymail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Benjamin',
    surName: 'Henderson',
    age: '27',
    email: 'benjamin_alan_henderson@hotmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Andrew',
    surName: 'Williams',
    age: '47',
    email: 'arwilliams@ymail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Sean',
    surName: 'Wright',
    age: '40',
    email: 's_wright@gmail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Anna',
    surName: 'Howard',
    age: '24',
    email: 'anna_m_howard@outlook.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Audrey',
    surName: 'Bryant',
    age: '47',
    email: 'audrey@rocketmail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Nathan',
    surName: 'Hughes',
    age: '42',
    email: 'nathan_hughes@aol.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Eric',
    surName: 'Miller',
    age: '62',
    email: 'e.m.miller@outlook.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Jose',
    surName: 'Ramirez',
    age: '53',
    email: 'josescottramirez38@hotmail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Theodore',
    surName: 'Lewis',
    age: '49',
    email: 'talewis@outlook.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Sophia',
    surName: 'Foster',
    age: '20',
    email: 'sophia_foster16@yahoo.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Zachary',
    surName: 'Reed',
    age: '45',
    email: 'zachary.reed@rocketmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Victoria',
    surName: 'Ramirez',
    age: '30',
    email: 'victoria_mary_ramirez@gmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'David',
    surName: 'Phillips',
    age: '21',
    email: 'david_phillips@hotmail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Alexis',
    surName: 'Diaz',
    age: '43',
    email: 'ardiaz66@yahoo.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Haley',
    surName: 'Davis',
    age: '65',
    email: 'haleymariedavis@yahoo.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Alexandra',
    surName: 'Anderson',
    age: '53',
    email: 'alexandra_m_anderson@outlook.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Richard',
    surName: 'Foster',
    age: '67',
    email: 'richard_ray_foster14@live.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Jack',
    surName: 'Morris',
    age: '57',
    email: 'j_morris@live.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Victoria',
    surName: 'Bailey',
    age: '59',
    email: 'victoriagracebailey@hotmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Olivia',
    surName: 'Sanchez',
    age: '59',
    email: 'oliviamsanchez@aol.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Michael',
    surName: 'Long',
    age: '23',
    email: 'michaeljosephlong@live.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Amber',
    surName: 'Brooks',
    age: '28',
    email: 'a.brooks17@outlook.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Kelsey',
    surName: 'Turner',
    age: '65',
    email: 'kelsey.turner@hotmail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Amber',
    surName: 'Cooper',
    age: '76',
    email: 'amber_cooper@ymail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Audrey',
    surName: 'Bennett',
    age: '44',
    email: 'a_bennett@gmail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Tiffany',
    surName: 'Moore',
    age: '41',
    email: 'tiffany@yahoo.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Christopher',
    surName: 'Cooper',
    age: '56',
    email: 'c_cooper@aol.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Amanda',
    surName: 'Hill',
    age: '60',
    email: 'a_hill8@gmail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Ethan',
    surName: 'Cook',
    age: '54',
    email: 'e.j@ymail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Nicole',
    surName: 'Flores',
    age: '39',
    email: 'nicole.s.flores@outlook.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Kayla',
    surName: 'Phillips',
    age: '68',
    email: 'kayla_l_phillips50@ymail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Jack',
    surName: 'Long',
    age: '34',
    email: 'jclong32@aol.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Maria',
    surName: 'Diaz',
    age: '64',
    email: 'm.diaz@yahoo.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Thomas',
    surName: 'Young',
    age: '65',
    email: 'thomas_young@outlook.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Tyler',
    surName: 'Cook',
    age: '45',
    email: 'tgcook18@rocketmail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Joshua',
    surName: 'Price',
    age: '53',
    email: 'joshuathomasprice@aol.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Joshua',
    surName: 'Evans',
    age: '77',
    email: 'j_evans29@ymail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Jose',
    surName: 'Bryant',
    age: '60',
    email: 'josejames@ymail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Kelsey',
    surName: 'Collins',
    age: '62',
    email: 'kelseym@yahoo.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Alexander',
    surName: 'Evans',
    age: '52',
    email: 'a_evans@yahoo.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Jasmine',
    surName: 'Ross',
    age: '49',
    email: 'jasmine_m_ross93@yahoo.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'William',
    surName: 'Lee',
    age: '69',
    email: 'wlee@ymail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Heather',
    surName: 'Scott',
    age: '61',
    email: 'h_scott@rocketmail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Kyle',
    surName: 'Hernandez',
    age: '27',
    email: 'kyle@live.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Timothy',
    surName: 'Howard',
    age: '48',
    email: 'timothyhoward@aol.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Charles',
    surName: 'Hughes',
    age: '35',
    email: 'charleshughes@outlook.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'William',
    surName: 'Carter',
    age: '74',
    email: 'williamcarter@gmail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'David',
    surName: 'Moore',
    age: '68',
    email: 'davidemoore@hotmail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Stephen',
    surName: 'Harris',
    age: '26',
    email: 'stephenrayharris@ymail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Benjamin',
    surName: 'King',
    age: '63',
    email: 'b_king@outlook.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Michael',
    surName: 'Taylor',
    age: '67',
    email: 'michaeljohntaylor@rocketmail.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Emma',
    surName: 'Peterson',
    age: '62',
    email: 'e.e.peterson@live.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Brian',
    surName: 'Watson',
    age: '24',
    email: 'brian_wayne@yahoo.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Samantha',
    surName: 'Smith',
    age: '47',
    email: 's_smith@outlook.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Timothy',
    surName: 'Jenkins',
    age: '46',
    email: 't_j_jenkins@aol.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Sebastian',
    surName: 'Coleman',
    age: '22',
    email: 'swcoleman@aol.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Steven',
    surName: 'Thompson',
    age: '61',
    email: 's_j@rocketmail.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Kelsey',
    surName: 'Bailey',
    age: '18',
    email: 'k_k_bailey@gmail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Kyle',
    surName: 'Jenkins',
    age: '53',
    email: 'kcjenkins@ymail.com',
    education: 'Less than high school',
  },
  {
    givenName: 'Evelyn',
    surName: 'Torres',
    age: '61',
    email: 'etorres@aol.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Maria',
    surName: 'Hernandez',
    age: '23',
    email: 'maria.hernandez@outlook.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Patrick',
    surName: 'Perez',
    age: '32',
    email: 'patrick@ymail.com',
    education: 'Bachelor’s degree',
  },
  {
    givenName: 'Natalie',
    surName: 'Wright',
    age: '68',
    email: 'nmwright27@live.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Sophia',
    surName: 'James',
    age: '42',
    email: 'sophia_r_james14@aol.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Jason',
    surName: 'Phillips',
    age: '77',
    email: 'j_s_phillips20@outlook.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Isabella',
    surName: 'Lee',
    age: '28',
    email: 'isabellasuelee@ymail.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Joseph',
    surName: 'Garcia',
    age: '53',
    email: 'josephgarcia@rocketmail.com',
    education: 'Doctoral degree',
  },
  {
    givenName: 'Emma',
    surName: 'Bennett',
    age: '67',
    email: 'ejbennett@outlook.com',
    education: 'High school diploma or equivalent',
  },
  {
    givenName: 'Timothy',
    surName: 'Bryant',
    age: '71',
    email: 'timothy.s.bryant@ymail.com',
    education: 'Some college, no degree',
  },
  {
    givenName: 'Jessica',
    surName: 'Butler',
    age: '70',
    email: 'j_m_butler@rocketmail.com',
    education: 'Master’s degree',
  },
  {
    givenName: 'Adam',
    surName: 'King',
    age: '49',
    email: 'a.king@live.com',
    education: 'Associate degree',
  },
  {
    givenName: 'Tyler',
    surName: 'Barnes',
    age: '67',
    email: 't.barnes@yahoo.com',
    education: 'Master’s degree',
  },
];
